### ISSUE TITLE
Support offset >= 16_777_216

### ISSUE THREAD

**Issue by johtani** [takuyaa/yada#15]
Hi,

We are using yada in Lindera.
I got an error from yada for building ipadic neologd dictionary with [lindera-ipadic-neologd-builder](https://github.com/lindera-morphology/lindera-ipadic-neologd-builder).
See the detail of error in [this PR](https://github.com/lindera-morphology/lindera-ipadic-neologd-builder/pull/11)

**Comment by takuyaa** [comment]
@johtani I released [yada 0.4.0](https://github.com/takuyaa/yada/blob/master/CHANGELOG.md#040---2020-10-11) that may allow you to construct a large double array (up to ~2GB). The limitation of maximum offset is now 536,870,911 which will be enough to build the mecab-ipadic-neologd dictionary.

I will close this issue, but please don't mind to reopen this issue or open other issues if you have any problems on 0.4.0.

**Comment by johtani** [comment]
Thanks!! I'll try to use it soon. :D
