### ISSUE TITLE
Add terminate char in builder?

### ISSUE THREAD

**Issue by johtani** [takuyaa/yada#4]
Now, the builder expects that keys have a terminal character. 
But, it is easy to use user only provides key and value.

What do you think?

**Comment by takuyaa** [comment]
Thank you for your cool feedback.
The keys must end with `\0` at this moment for simplicity of `DoubleArrayBuilder`.
But I agree with your suggestion that the keys don't need a `\0`, which is easier to build a double array.
I will try to improve it.

**Comment by takuyaa** [comment]
@johtani I published a new version `0.3.0` which does not require us to append the `\0` anymore. Please take a look.
https://crates.io/crates/yada
